import "./globals.css";
import { stackSans, openSans } from "./fonts";
import { Navigation6 } from "@/components/navigation-6";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="de" className={`${stackSans.variable} ${openSans.variable}`}>
      <body className="bg-white text-black font-sans antialiased">
        <Navigation6 />
        {children}
      </body>
    </html>
  );
}
