export const siteConfig = {
  name: "Freccia Rossa",
  title: "Autoaufbereitung Magdeburg | Freccia Rossa",
  description:
    "Professionelle Autoaufbereitung in Magdeburg: Handwäsche, Politur, Lackversiegelung und Innenraumaufbereitung für PKW, Oldtimer, Wohnmobil und Motorrad – von Hand, mit Sorgfalt.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://freccia-rossa.de",
  phone: "+493911234567",
  phoneDisplay: "+49 391 123 456 7",
  email: "info@freccia-rossa.de",
  locality: "Magdeburg",
  geo: { latitude: 52.143243, longitude: 11.637635 },
  ogImage: "/og-image.png",
  logo: "/video/bilder/logo-weiss.png",
  photo: "/bilder/Aufbereitung-AMG.webp",
  openingHours: "Mo-Sa 08:00-17:00",
  openingHoursDisplay: "Mo–Sa 8–17 Uhr",
  openingHoursByDay: [
    { day: "Montag", hours: "8:00 – 17:00 Uhr" },
    { day: "Dienstag", hours: "8:00 – 17:00 Uhr" },
    { day: "Mittwoch", hours: "8:00 – 17:00 Uhr" },
    { day: "Donnerstag", hours: "8:00 – 17:00 Uhr" },
    { day: "Freitag", hours: "8:00 – 17:00 Uhr" },
    { day: "Samstag", hours: "8:00 – 17:00 Uhr" },
    { day: "Sonntag", hours: "Geschlossen" },
  ],
};
